version: "3"
services:
    db:
      container_name: db
      image: mongo
      ports:
       - "27017:27017"  
      volumes:
       - ./.data:/data/db
    api:
      container_name: api
      build: .
      ports :
       - "3000:3000"
      volumes:
        - ./:/home/node/app
